<a href="https://colab.research.google.com/github/taehohoho/LESSON/blob/master/210809_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.shape

(5,)

In [ ]:
arr + 2

array([3, 4, 5, 6, 7])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
arr[:2]

array([1, 2])

In [ ]:
arr[3:5]

array([4, 5])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 3, 11)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. ])

In [ ]:
arr2 = np.array([[1,3],
                 [5,7]])
arr2

array([[1, 3],
       [5, 7]])

In [ ]:
arr2.shape

(2, 2)

In [ ]:
np.save('test.npy', arr2)

In [ ]:
np.load('test.npy')

array([[1, 3],
       [5, 7]])