<a href="https://colab.research.google.com/github/taehohoho/LESSON/blob/master/210806_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a2.dtype

dtype('float64')

In [ ]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [ ]:
np.array([[1,2,3], [4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [ ]:
b2 = np.arange(5)
b2.shape

(5,)

In [ ]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [26]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [27]:
str_a1.dtype

dtype('<U5')

In [28]:
num_a1.dtype

dtype('float64')

In [29]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [30]:
str_a2.dtype

dtype('<U1')

In [31]:
num_a2.dtype

dtype('int64')

In [32]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [33]:
num_f1.dtype

dtype('float64')

In [34]:
num_i1.dtype

dtype('int64')

In [35]:
np.random.rand(2,3)

array([[0.04041793, 0.53590989, 0.07658504],
       [0.06013567, 0.49832174, 0.58680434]])

In [36]:
np.random.rand()

0.35817485408530425

In [37]:
np.random.rand(2,3,4)

array([[[0.88044827, 0.64292896, 0.59998659, 0.04823498],
        [0.86295026, 0.84887782, 0.59643197, 0.57216855],
        [0.88245473, 0.72803929, 0.73276099, 0.17646861]],

       [[0.11283645, 0.45303519, 0.98160493, 0.97608743],
        [0.3159841 , 0.72685058, 0.57638288, 0.02841962],
        [0.40291998, 0.59776485, 0.9643415 , 0.91717732]]])

In [38]:
np.random.randint(10, size=(3,4))

array([[9, 0, 0, 5],
       [1, 5, 4, 8],
       [3, 3, 0, 5]])

In [39]:
np.random.randint(1,30)

23

In [40]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1,2,3,4])

In [41]:
arr1 + arr2

array([11, 22, 33, 44])

In [42]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [43]:
arr2 * 2

array([2, 4, 6, 8])

In [44]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [45]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [46]:
arr1 / arr2

array([10., 10., 10., 10.])

In [47]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [48]:
arr1 > 20

array([False, False,  True,  True])

In [49]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [50]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [51]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [52]:
[arr3.min(), arr3.max()]

[0, 4]

In [53]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [54]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [55]:
arr4.cumprod()

array([ 1,  2,  6, 24])

In [56]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [57]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [58]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [59]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [60]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [61]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [62]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [63]:
np.linalg.det(A)

-2.0

In [64]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [65]:
a1[0]

0

In [66]:
a1[4]

40

In [67]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [68]:
a1[[1,3,4]]

array([10, 30, 40])

In [69]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [70]:
a2[0,2]

30

In [71]:
a2[2,2]=95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [72]:
a2[1]

array([40, 50, 60])

In [73]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [74]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [75]:
a2[[0,2],[0,1]]

array([10, 80])

In [76]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [78]:
a[(a % 2)] == 0

array([False, False, False, False, False, False])

In [80]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [81]:
b1[:3]

array([ 0, 10, 20])

In [82]:
b1[2:]

array([20, 30, 40, 50])

In [83]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [84]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [86]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [87]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [88]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [89]:
b2[1][0:2]

array([40, 50])

In [91]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])