<a href="https://colab.research.google.com/github/taehohoho/LESSON/blob/master/210810_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# jupyter notebook의 출력을 소수점 이하 3자리로 제한
%precision 3
# dataframe의 출력을 소수점 이하 3자리로 제한
pd.set_option('precision', 3)

In [ ]:
df = pd.read_csv('scores_em.csv', index_col = 'student number')
# df의 처음 5행을 표시
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [ ]:
scores = np.array(df['english'][:10])
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [ ]:
scores_df = pd.DataFrame({'score':scores},index=pd.Index(['A','B','C','D','E','F','G','H','I','J'], name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [ ]:
sum(scores) / len(scores)

55.000

In [ ]:
np.mean(scores)

55.000

In [ ]:
scores_df.mean()

score    55.0
dtype: float64

In [ ]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [ ]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2 -1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) /2
else:
    median = sorted_scores[(n+1)//2 -1]
median

56.500

In [ ]:
np.median(scores)

56.500

In [ ]:
scores_df.median()

score    56.5
dtype: float64

In [ ]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [ ]:
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
mean = np.mean(scores)
deviation = scores - median
deviation

array([-14.5,  12.5,  -0.5, -15.5,   0.5,  -8.5,   8.5,  -7.5,   8.5,
         1.5])

In [ ]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59 ]
another_mean = np.mean(another_scores)
another_deviation = another_scores = another_mean
another_deviation

55.000

In [ ]:
np.mean(deviation)

-1.500

In [ ]:
np.mean(another_deviation)

55.000

In [ ]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -14.5
B           69       12.5
C           56       -0.5
D           41      -15.5
E           57        0.5
F           48       -8.5
G           65        8.5
H           49       -7.5
I           65        8.5
J           58        1.5

In [ ]:
summary_df.mean()

score        55.0
deviation    -1.5
dtype: float64

In [ ]:
np.mean(deviation ** 2)

88.250

In [ ]:
np.var(scores)

86.000

In [ ]:
scores_df.var()

score    95.556
dtype: float64

In [ ]:
summary_df['square of deviaion'] = np.square(deviation)
summary_df

score  deviation  square of deviaion
student                                      
A           42      -14.5              210.25
B           69       12.5              156.25
C           56       -0.5                0.25
D           41      -15.5              240.25
E           57        0.5                0.25
F           48       -8.5               72.25
G           65        8.5               72.25
H           49       -7.5               56.25
I           65        8.5               72.25
J           58        1.5                2.25

In [ ]:
summary_df.mean()

score                 55.00
deviation             -1.50
square of deviaion    88.25
dtype: float64

In [ ]:
np.sqrt(np.var(scores, ddof = 0))

9.274

In [ ]:
np.std(scores, ddof = 0)

9.274